// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package acme_external_account_binding

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/acm"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/acm/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/acm-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.AcmeExternalAccountBinding{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeAcmeExternalAccountBindingOutput
	resp, err = rm.sdkapi.DescribeAcmeExternalAccountBinding(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeAcmeExternalAccountBinding", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.ExternalAccountBinding.AcmeEndpointArn != nil {
		ko.Spec.AcmeEndpointARN = resp.ExternalAccountBinding.AcmeEndpointArn
	} else {
		ko.Spec.AcmeEndpointARN = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ExternalAccountBinding.AcmeExternalAccountBindingArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ExternalAccountBinding.AcmeExternalAccountBindingArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ExternalAccountBinding.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.ExternalAccountBinding.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.ExternalAccountBinding.ExpiresAt != nil {
		ko.Status.ExpiresAt = &metav1.Time{*resp.ExternalAccountBinding.ExpiresAt}
	} else {
		ko.Status.ExpiresAt = nil
	}
	if resp.ExternalAccountBinding.LastUsedAt != nil {
		ko.Status.LastUsedAt = &metav1.Time{*resp.ExternalAccountBinding.LastUsedAt}
	} else {
		ko.Status.LastUsedAt = nil
	}
	if resp.ExternalAccountBinding.RevokedAt != nil {
		ko.Status.RevokedAt = &metav1.Time{*resp.ExternalAccountBinding.RevokedAt}
	} else {
		ko.Status.RevokedAt = nil
	}
	if resp.ExternalAccountBinding.RoleArn != nil {
		ko.Spec.RoleARN = resp.ExternalAccountBinding.RoleArn
	} else {
		ko.Spec.RoleARN = nil
	}
	if resp.ExternalAccountBinding.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.ExternalAccountBinding.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	ko.Spec.Tags, err = listTags(
		ctx, rm.sdkapi, rm.metrics,
		string(*r.ko.Status.ACKResourceMetadata.ARN),
	)
	if err != nil {
		return nil, err
	}

	// Repair a binding whose credentials never reached the Secret or status — the create
	// pass can fail after the binding exists (a Secret that does not exist yet, a denied
	// credentials call, a throttle), and a user can add spec.credentialsOutput or empty the
	// Secret later. needsCredentials reads the Secret rather than trusting status, so the
	// steady state costs one Kubernetes read and no AWS call.
	//
	// NOT while the resource is being deleted. The runtime's delete path calls ReadOne
	// FIRST and abandons the delete on any error that is not NotFound, so a repair that
	// fails here would stop DeleteAcmeExternalAccountBinding from ever being called: the CR
	// would sit in Terminating for ever (taking its namespace with it) and the binding would
	// be left live in ACM. That happens for real whenever the Secret is removed before the
	// CR — GitOps pruning, or a namespace deletion, where the Secret has no finalizer and
	// goes immediately while this resource waits on ours. There is nothing to repair on a
	// resource that is going away.
	if r.ko.DeletionTimestamp.IsZero() {
		needs, err := rm.needsCredentials(ctx, ko)
		if err != nil {
			// The Secret cannot be read at all — a non-Opaque type, or a cross-namespace
			// reference the operator has not enabled. Report it, rather than treating it as
			// "not stored" and re-fetching the credential from AWS on every pass.
			return &resource{ko}, err
		}
		if needs {
			if err := rm.storeEABCredentials(ctx, ko); err != nil {
				return &resource{ko}, err
			}
		}
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return (r.ko.Status.ACKResourceMetadata == nil || r.ko.Status.ACKResourceMetadata.ARN == nil)

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeAcmeExternalAccountBindingInput, error) {
	res := &svcsdk.DescribeAcmeExternalAccountBindingInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.AcmeExternalAccountBindingArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateAcmeExternalAccountBindingOutput
	_ = resp
	resp, err = rm.sdkapi.CreateAcmeExternalAccountBinding(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateAcmeExternalAccountBinding", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ExternalAccountBinding.AcmeEndpointArn != nil {
		ko.Spec.AcmeEndpointARN = resp.ExternalAccountBinding.AcmeEndpointArn
	} else {
		ko.Spec.AcmeEndpointARN = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ExternalAccountBinding.AcmeExternalAccountBindingArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ExternalAccountBinding.AcmeExternalAccountBindingArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ExternalAccountBinding.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.ExternalAccountBinding.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.ExternalAccountBinding.ExpiresAt != nil {
		ko.Status.ExpiresAt = &metav1.Time{*resp.ExternalAccountBinding.ExpiresAt}
	} else {
		ko.Status.ExpiresAt = nil
	}
	if resp.ExternalAccountBinding.LastUsedAt != nil {
		ko.Status.LastUsedAt = &metav1.Time{*resp.ExternalAccountBinding.LastUsedAt}
	} else {
		ko.Status.LastUsedAt = nil
	}
	if resp.ExternalAccountBinding.RevokedAt != nil {
		ko.Status.RevokedAt = &metav1.Time{*resp.ExternalAccountBinding.RevokedAt}
	} else {
		ko.Status.RevokedAt = nil
	}
	if resp.ExternalAccountBinding.RoleArn != nil {
		ko.Spec.RoleARN = resp.ExternalAccountBinding.RoleArn
	} else {
		ko.Spec.RoleARN = nil
	}
	if resp.ExternalAccountBinding.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.ExternalAccountBinding.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	// Record the credentials: the key identifier in status, and the secret MAC key in
	// the Secret named by spec.credentialsOutput. They are only available from
	// GetAcmeExternalAccountBindingCredentials, so this cannot be part of the create
	// response handling.
	//
	// Failures are returned as a requeue rather than as an AWS error, and the resource is
	// returned rather than nil: the binding already exists in ACM at this point, so
	// discarding it (nil) or surfacing an AWS error (which makes the runtime mark the
	// resource unmanaged and drop the finalizer) would orphan a live credential.
	if err := rm.storeEABCredentials(ctx, ko); err != nil {
		return &resource{ko}, err
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateAcmeExternalAccountBindingInput, error) {
	res := &svcsdk.CreateAcmeExternalAccountBindingInput{}

	if r.ko.Spec.AcmeEndpointARN != nil {
		res.AcmeEndpointArn = r.ko.Spec.AcmeEndpointARN
	}
	if r.ko.Spec.Expiration != nil {
		f1 := &svcsdktypes.Expiration{}
		if r.ko.Spec.Expiration.Type != nil {
			f1.Type = svcsdktypes.TimeType(*r.ko.Spec.Expiration.Type)
		}
		if r.ko.Spec.Expiration.Value != nil {
			f1.Value = r.ko.Spec.Expiration.Value
		}
		res.Expiration = f1
	}
	if r.ko.Spec.RoleARN != nil {
		res.RoleArn = r.ko.Spec.RoleARN
	}
	if r.ko.Spec.Tags != nil {
		f3 := []svcsdktypes.Tag{}
		for _, f3iter := range r.ko.Spec.Tags {
			f3elem := &svcsdktypes.Tag{}
			if f3iter.Key != nil {
				f3elem.Key = f3iter.Key
			}
			if f3iter.Value != nil {
				f3elem.Value = f3iter.Value
			}
			f3 = append(f3, *f3elem)
		}
		res.Tags = f3
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateAcmeExternalAccountBinding(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteAcmeExternalAccountBindingOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteAcmeExternalAccountBinding(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteAcmeExternalAccountBinding", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteAcmeExternalAccountBindingInput, error) {
	res := &svcsdk.DeleteAcmeExternalAccountBindingInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.AcmeExternalAccountBindingArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.AcmeExternalAccountBinding,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	if syncCondition == nil && onSuccess {
		syncCondition = &ackv1alpha1.Condition{
			Type:   ackv1alpha1.ConditionTypeResourceSynced,
			Status: corev1.ConditionTrue,
		}
		ko.Status.Conditions = append(ko.Status.Conditions, syncCondition)
	}
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterException",
		"InvalidArnException",
		"InvalidTagException",
		"TagPolicyException",
		"TooManyTagsException",
		"ValidationException":
		return true
	default:
		return false
	}
}
