// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package acme_domain_validation

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/acm"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/acm/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/acm-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.AcmeDomainValidation{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeAcmeDomainValidationOutput
	resp, err = rm.sdkapi.DescribeAcmeDomainValidation(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeAcmeDomainValidation", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.AcmeDomainValidation.AcmeDomainValidationArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.AcmeDomainValidation.AcmeDomainValidationArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.AcmeDomainValidation.AcmeEndpointArn != nil {
		ko.Spec.AcmeEndpointARN = resp.AcmeDomainValidation.AcmeEndpointArn
	} else {
		ko.Spec.AcmeEndpointARN = nil
	}
	if resp.AcmeDomainValidation.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.AcmeDomainValidation.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.AcmeDomainValidation.DomainName != nil {
		ko.Spec.DomainName = resp.AcmeDomainValidation.DomainName
	} else {
		ko.Spec.DomainName = nil
	}
	if resp.AcmeDomainValidation.FailureDetails != nil {
		f4 := &svcapitypes.FailureDetails{}
		if resp.AcmeDomainValidation.FailureDetails.Message != nil {
			f4.Message = resp.AcmeDomainValidation.FailureDetails.Message
		}
		if resp.AcmeDomainValidation.FailureDetails.Reason != "" {
			f4.Reason = aws.String(string(resp.AcmeDomainValidation.FailureDetails.Reason))
		}
		ko.Status.FailureDetails = f4
	} else {
		ko.Status.FailureDetails = nil
	}
	if resp.AcmeDomainValidation.PrevalidationDetails != nil {
		f5 := &svcapitypes.PrevalidationDetails{}
		switch resp.AcmeDomainValidation.PrevalidationDetails.(type) {
		case *svcsdktypes.PrevalidationDetailsMemberDnsPrevalidation:
			f5f0 := resp.AcmeDomainValidation.PrevalidationDetails.(*svcsdktypes.PrevalidationDetailsMemberDnsPrevalidation)
			if f5f0 != nil {
				f5f0f0 := &svcapitypes.DNSPrevalidationDetails{}
				if f5f0.Value.DomainScope != nil {
					f5f0f0f0 := &svcapitypes.DomainScope{}
					if f5f0.Value.DomainScope.ExactDomain != "" {
						f5f0f0f0.ExactDomain = aws.String(string(f5f0.Value.DomainScope.ExactDomain))
					}
					if f5f0.Value.DomainScope.Subdomains != "" {
						f5f0f0f0.Subdomains = aws.String(string(f5f0.Value.DomainScope.Subdomains))
					}
					if f5f0.Value.DomainScope.Wildcards != "" {
						f5f0f0f0.Wildcards = aws.String(string(f5f0.Value.DomainScope.Wildcards))
					}
					f5f0f0.DomainScope = f5f0f0f0
				}
				if f5f0.Value.HostedZoneId != nil {
					f5f0f0.HostedZoneID = f5f0.Value.HostedZoneId
				}
				if f5f0.Value.ResourceRecord != nil {
					f5f0f0f2 := &svcapitypes.ResourceRecord{}
					if f5f0.Value.ResourceRecord.Name != nil {
						f5f0f0f2.Name = f5f0.Value.ResourceRecord.Name
					}
					if f5f0.Value.ResourceRecord.Type != "" {
						f5f0f0f2.Type = aws.String(string(f5f0.Value.ResourceRecord.Type))
					}
					if f5f0.Value.ResourceRecord.Value != nil {
						f5f0f0f2.Value = f5f0.Value.ResourceRecord.Value
					}
					f5f0f0.ResourceRecord = f5f0f0f2
				}
				f5.DNSPrevalidation = f5f0f0
			}
		}
		ko.Status.PrevalidationDetails = f5
	} else {
		ko.Status.PrevalidationDetails = nil
	}
	if resp.AcmeDomainValidation.PrevalidationType != "" {
		ko.Status.PrevalidationType = aws.String(string(resp.AcmeDomainValidation.PrevalidationType))
	} else {
		ko.Status.PrevalidationType = nil
	}
	if resp.AcmeDomainValidation.Status != "" {
		ko.Status.Status = aws.String(string(resp.AcmeDomainValidation.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.AcmeDomainValidation.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.AcmeDomainValidation.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	ko.Spec.Tags, err = listTags(
		ctx, rm.sdkapi, rm.metrics,
		string(*r.ko.Status.ACKResourceMetadata.ARN),
	)
	if err != nil {
		return nil, err
	}
	// DescribeAcmeDomainValidation does not echo the PrevalidationOptions
	// input; it reports the effective prevalidation state in
	// PrevalidationDetails. Reconstruct spec.prevalidationOptions from those
	// details so the delta compares the actual service state: a user edit to
	// prevalidationOptions then produces a real diff and reconciles via
	// UpdateAcmeDomainValidation, while an unchanged spec produces none.
	if ko.Status.PrevalidationDetails != nil &&
		ko.Status.PrevalidationDetails.DNSPrevalidation != nil {
		details := ko.Status.PrevalidationDetails.DNSPrevalidation
		ko.Spec.PrevalidationOptions = &svcapitypes.PrevalidationOptions{
			DNSPrevalidation: &svcapitypes.DNSPrevalidationOptions{
				DomainScope:  details.DomainScope,
				HostedZoneID: details.HostedZoneID,
			},
		}
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return (r.ko.Status.ACKResourceMetadata == nil || r.ko.Status.ACKResourceMetadata.ARN == nil)

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeAcmeDomainValidationInput, error) {
	res := &svcsdk.DescribeAcmeDomainValidationInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.AcmeDomainValidationArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateAcmeDomainValidationOutput
	_ = resp
	resp, err = rm.sdkapi.CreateAcmeDomainValidation(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateAcmeDomainValidation", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.AcmeDomainValidationArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.AcmeDomainValidationArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateAcmeDomainValidationInput, error) {
	res := &svcsdk.CreateAcmeDomainValidationInput{}

	if r.ko.Spec.AcmeEndpointARN != nil {
		res.AcmeEndpointArn = r.ko.Spec.AcmeEndpointARN
	}
	if r.ko.Spec.DomainName != nil {
		res.DomainName = r.ko.Spec.DomainName
	}
	if r.ko.Spec.PrevalidationOptions != nil {
		var f2 svcsdktypes.PrevalidationOptions
		isInterfaceSet := false
		if r.ko.Spec.PrevalidationOptions.DNSPrevalidation != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for DnsPrevalidation"))
			}
			f2f0Parent := &svcsdktypes.PrevalidationOptionsMemberDnsPrevalidation{}
			f2f0 := &svcsdktypes.DnsPrevalidationOptions{}
			if r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope != nil {
				f2f0f0 := &svcsdktypes.DomainScope{}
				if r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope.ExactDomain != nil {
					f2f0f0.ExactDomain = svcsdktypes.DomainScopeOption(*r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope.ExactDomain)
				}
				if r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope.Subdomains != nil {
					f2f0f0.Subdomains = svcsdktypes.DomainScopeOption(*r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope.Subdomains)
				}
				if r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope.Wildcards != nil {
					f2f0f0.Wildcards = svcsdktypes.DomainScopeOption(*r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope.Wildcards)
				}
				f2f0.DomainScope = f2f0f0
			}
			if r.ko.Spec.PrevalidationOptions.DNSPrevalidation.HostedZoneID != nil {
				f2f0.HostedZoneId = r.ko.Spec.PrevalidationOptions.DNSPrevalidation.HostedZoneID
			}
			f2f0Parent.Value = *f2f0
			f2 = f2f0Parent
			isInterfaceSet = true
		}
		res.PrevalidationOptions = f2
	}
	if r.ko.Spec.Tags != nil {
		f3 := []svcsdktypes.Tag{}
		for _, f3iter := range r.ko.Spec.Tags {
			f3elem := &svcsdktypes.Tag{}
			if f3iter.Key != nil {
				f3elem.Key = f3iter.Key
			}
			if f3iter.Value != nil {
				f3elem.Value = f3iter.Value
			}
			f3 = append(f3, *f3elem)
		}
		res.Tags = f3
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		if err := syncTags(
			ctx, rm.sdkapi, rm.metrics,
			string(*desired.ko.Status.ACKResourceMetadata.ARN),
			desired.ko.Spec.Tags, latest.ko.Spec.Tags,
		); err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}
	// UpdateAcmeDomainValidation is rejected while validation is in progress
	// (VALIDATING). Mark the resource as not synced with a message and
	// requeue until validation settles.
	if !domainValidationModifiable(latest) {
		updatedRes := rm.concreteResource(desired.DeepCopy())
		updatedRes.SetStatus(latest)
		msg := "Domain validation is in '" + *latest.ko.Status.Status + "' status"
		ackcondition.SetSynced(updatedRes, corev1.ConditionFalse, &msg, nil)
		return updatedRes, requeueWaitUntilCanModify(latest)
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateAcmeDomainValidationOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateAcmeDomainValidation(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateAcmeDomainValidation", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateAcmeDomainValidationInput, error) {
	res := &svcsdk.UpdateAcmeDomainValidationInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.AcmeDomainValidationArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Spec.PrevalidationOptions != nil {
		var f1 svcsdktypes.PrevalidationOptions
		isInterfaceSet := false
		if r.ko.Spec.PrevalidationOptions.DNSPrevalidation != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for DnsPrevalidation"))
			}
			f1f0Parent := &svcsdktypes.PrevalidationOptionsMemberDnsPrevalidation{}
			f1f0 := &svcsdktypes.DnsPrevalidationOptions{}
			if r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope != nil {
				f1f0f0 := &svcsdktypes.DomainScope{}
				if r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope.ExactDomain != nil {
					f1f0f0.ExactDomain = svcsdktypes.DomainScopeOption(*r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope.ExactDomain)
				}
				if r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope.Subdomains != nil {
					f1f0f0.Subdomains = svcsdktypes.DomainScopeOption(*r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope.Subdomains)
				}
				if r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope.Wildcards != nil {
					f1f0f0.Wildcards = svcsdktypes.DomainScopeOption(*r.ko.Spec.PrevalidationOptions.DNSPrevalidation.DomainScope.Wildcards)
				}
				f1f0.DomainScope = f1f0f0
			}
			if r.ko.Spec.PrevalidationOptions.DNSPrevalidation.HostedZoneID != nil {
				f1f0.HostedZoneId = r.ko.Spec.PrevalidationOptions.DNSPrevalidation.HostedZoneID
			}
			f1f0Parent.Value = *f1f0
			f1 = f1f0Parent
			isInterfaceSet = true
		}
		res.PrevalidationOptions = f1
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteAcmeDomainValidationOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteAcmeDomainValidation(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteAcmeDomainValidation", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteAcmeDomainValidationInput, error) {
	res := &svcsdk.DeleteAcmeDomainValidationInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.AcmeDomainValidationArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.AcmeDomainValidation,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterException",
		"InvalidArnException",
		"InvalidTagException",
		"TagPolicyException",
		"TooManyTagsException",
		"ValidationException":
		return true
	default:
		return false
	}
}
