---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-acm-reader
  namespace: default
rules:
- apiGroups:
  - acm.services.k8s.aws
  resources:
  - certificates
  verbs:
  - get
  - list
  - watch
