// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package acme_endpoint

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/acm"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/acm/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/acm-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.AcmeEndpoint{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeAcmeEndpointOutput
	resp, err = rm.sdkapi.DescribeAcmeEndpoint(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeAcmeEndpoint", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.AcmeEndpoint.AcmeEndpointArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.AcmeEndpoint.AcmeEndpointArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.AcmeEndpoint.AuthorizationBehavior != "" {
		ko.Spec.AuthorizationBehavior = aws.String(string(resp.AcmeEndpoint.AuthorizationBehavior))
	} else {
		ko.Spec.AuthorizationBehavior = nil
	}
	if resp.AcmeEndpoint.CertificateAuthority != nil {
		f2 := &svcapitypes.CertificateAuthority{}
		switch resp.AcmeEndpoint.CertificateAuthority.(type) {
		case *svcsdktypes.CertificateAuthorityMemberPublicCertificateAuthority:
			f2f0 := resp.AcmeEndpoint.CertificateAuthority.(*svcsdktypes.CertificateAuthorityMemberPublicCertificateAuthority)
			if f2f0 != nil {
				f2f0f0 := &svcapitypes.PublicCertificateAuthority{}
				if f2f0.Value.AllowedKeyAlgorithms != nil {
					f2f0f0f0 := []*string{}
					for _, f2f0f0f0iter := range f2f0.Value.AllowedKeyAlgorithms {
						var f2f0f0f0elem *string
						f2f0f0f0elem = aws.String(string(f2f0f0f0iter))
						f2f0f0f0 = append(f2f0f0f0, f2f0f0f0elem)
					}
					f2f0f0.AllowedKeyAlgorithms = f2f0f0f0
				}
				f2.PublicCertificateAuthority = f2f0f0
			}
		}
		ko.Spec.CertificateAuthority = f2
	} else {
		ko.Spec.CertificateAuthority = nil
	}
	if resp.AcmeEndpoint.CertificateTags != nil {
		f3 := []*svcapitypes.Tag{}
		for _, f3iter := range resp.AcmeEndpoint.CertificateTags {
			f3elem := &svcapitypes.Tag{}
			if f3iter.Key != nil {
				f3elem.Key = f3iter.Key
			}
			if f3iter.Value != nil {
				f3elem.Value = f3iter.Value
			}
			f3 = append(f3, f3elem)
		}
		ko.Spec.CertificateTags = f3
	} else {
		ko.Spec.CertificateTags = nil
	}
	if resp.AcmeEndpoint.Contact != "" {
		ko.Spec.Contact = aws.String(string(resp.AcmeEndpoint.Contact))
	} else {
		ko.Spec.Contact = nil
	}
	if resp.AcmeEndpoint.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.AcmeEndpoint.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.AcmeEndpoint.EndpointUrl != nil {
		ko.Status.EndpointURL = resp.AcmeEndpoint.EndpointUrl
	} else {
		ko.Status.EndpointURL = nil
	}
	if resp.AcmeEndpoint.FailureReason != nil {
		ko.Status.FailureReason = resp.AcmeEndpoint.FailureReason
	} else {
		ko.Status.FailureReason = nil
	}
	if resp.AcmeEndpoint.Status != "" {
		ko.Status.Status = aws.String(string(resp.AcmeEndpoint.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.AcmeEndpoint.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.AcmeEndpoint.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	ko.Spec.Tags, err = listTags(
		ctx, rm.sdkapi, rm.metrics,
		string(*r.ko.Status.ACKResourceMetadata.ARN),
	)
	if err != nil {
		return nil, err
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return (r.ko.Status.ACKResourceMetadata == nil || r.ko.Status.ACKResourceMetadata.ARN == nil)

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeAcmeEndpointInput, error) {
	res := &svcsdk.DescribeAcmeEndpointInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.AcmeEndpointArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateAcmeEndpointOutput
	_ = resp
	resp, err = rm.sdkapi.CreateAcmeEndpoint(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateAcmeEndpoint", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.AcmeEndpointArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.AcmeEndpointArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateAcmeEndpointInput, error) {
	res := &svcsdk.CreateAcmeEndpointInput{}

	if r.ko.Spec.AuthorizationBehavior != nil {
		res.AuthorizationBehavior = svcsdktypes.AcmeAuthorizationBehavior(*r.ko.Spec.AuthorizationBehavior)
	}
	if r.ko.Spec.CertificateAuthority != nil {
		var f1 svcsdktypes.CertificateAuthority
		isInterfaceSet := false
		if r.ko.Spec.CertificateAuthority.PublicCertificateAuthority != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for PublicCertificateAuthority"))
			}
			f1f0Parent := &svcsdktypes.CertificateAuthorityMemberPublicCertificateAuthority{}
			f1f0 := &svcsdktypes.PublicCertificateAuthority{}
			if r.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms != nil {
				f1f0f0 := []svcsdktypes.PublicKeyAlgorithm{}
				for _, f1f0f0iter := range r.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms {
					var f1f0f0elem string
					f1f0f0elem = string(*f1f0f0iter)
					f1f0f0 = append(f1f0f0, svcsdktypes.PublicKeyAlgorithm(f1f0f0elem))
				}
				f1f0.AllowedKeyAlgorithms = f1f0f0
			}
			f1f0Parent.Value = *f1f0
			f1 = f1f0Parent
			isInterfaceSet = true
		}
		res.CertificateAuthority = f1
	}
	if r.ko.Spec.CertificateTags != nil {
		f2 := []svcsdktypes.Tag{}
		for _, f2iter := range r.ko.Spec.CertificateTags {
			f2elem := &svcsdktypes.Tag{}
			if f2iter.Key != nil {
				f2elem.Key = f2iter.Key
			}
			if f2iter.Value != nil {
				f2elem.Value = f2iter.Value
			}
			f2 = append(f2, *f2elem)
		}
		res.CertificateTags = f2
	}
	if r.ko.Spec.Contact != nil {
		res.Contact = svcsdktypes.AcmeContact(*r.ko.Spec.Contact)
	}
	if r.ko.Spec.Tags != nil {
		f4 := []svcsdktypes.Tag{}
		for _, f4iter := range r.ko.Spec.Tags {
			f4elem := &svcsdktypes.Tag{}
			if f4iter.Key != nil {
				f4elem.Key = f4iter.Key
			}
			if f4iter.Value != nil {
				f4elem.Value = f4iter.Value
			}
			f4 = append(f4, *f4elem)
		}
		res.Tags = f4
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		if err := syncTags(
			ctx, rm.sdkapi, rm.metrics,
			string(*desired.ko.Status.ACKResourceMetadata.ARN),
			desired.ko.Spec.Tags, latest.ko.Spec.Tags,
		); err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}
	// UpdateAcmeEndpoint is only valid against an ACTIVE endpoint. Mark the
	// resource as not synced with a message and requeue until it can be
	// modified.
	if !endpointActive(latest) {
		updatedRes := rm.concreteResource(desired.DeepCopy())
		updatedRes.SetStatus(latest)
		msg := "Endpoint is in '" + *latest.ko.Status.Status + "' status"
		ackcondition.SetSynced(updatedRes, corev1.ConditionFalse, &msg, nil)
		return updatedRes, requeueWaitUntilCanModify(latest)
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateAcmeEndpointOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateAcmeEndpoint(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateAcmeEndpoint", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateAcmeEndpointInput, error) {
	res := &svcsdk.UpdateAcmeEndpointInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.AcmeEndpointArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Spec.AuthorizationBehavior != nil {
		res.AuthorizationBehavior = svcsdktypes.AcmeAuthorizationBehavior(*r.ko.Spec.AuthorizationBehavior)
	}
	if r.ko.Spec.CertificateAuthority != nil {
		var f2 svcsdktypes.CertificateAuthority
		isInterfaceSet := false
		if r.ko.Spec.CertificateAuthority.PublicCertificateAuthority != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for PublicCertificateAuthority"))
			}
			f2f0Parent := &svcsdktypes.CertificateAuthorityMemberPublicCertificateAuthority{}
			f2f0 := &svcsdktypes.PublicCertificateAuthority{}
			if r.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms != nil {
				f2f0f0 := []svcsdktypes.PublicKeyAlgorithm{}
				for _, f2f0f0iter := range r.ko.Spec.CertificateAuthority.PublicCertificateAuthority.AllowedKeyAlgorithms {
					var f2f0f0elem string
					f2f0f0elem = string(*f2f0f0iter)
					f2f0f0 = append(f2f0f0, svcsdktypes.PublicKeyAlgorithm(f2f0f0elem))
				}
				f2f0.AllowedKeyAlgorithms = f2f0f0
			}
			f2f0Parent.Value = *f2f0
			f2 = f2f0Parent
			isInterfaceSet = true
		}
		res.CertificateAuthority = f2
	}
	if r.ko.Spec.Contact != nil {
		res.Contact = svcsdktypes.AcmeContact(*r.ko.Spec.Contact)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteAcmeEndpointOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteAcmeEndpoint(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteAcmeEndpoint", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteAcmeEndpointInput, error) {
	res := &svcsdk.DeleteAcmeEndpointInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.AcmeEndpointArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.AcmeEndpoint,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	if syncCondition == nil && onSuccess {
		syncCondition = &ackv1alpha1.Condition{
			Type:   ackv1alpha1.ConditionTypeResourceSynced,
			Status: corev1.ConditionTrue,
		}
		ko.Status.Conditions = append(ko.Status.Conditions, syncCondition)
	}
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterException",
		"InvalidArnException",
		"InvalidTagException",
		"TagPolicyException",
		"TooManyTagsException",
		"ValidationException":
		return true
	default:
		return false
	}
}
