# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS ACM controller is a service controller for managing ACM resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon ACM
description: |-
  Manage Amazon ACM resources in AWS from within your Kubernetes cluster.


  **About Amazon ACM**


  {ADD YOUR DESCRIPTION HERE}


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.
samples:
- kind: ExampleCustomKind
  spec: '{}'
- kind: SecondExampleCustomKind
  spec: '{}'
maintainers:
- name: "acm maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon ACM Developer Resources
  url: https://aws.amazon.com/ACM/developer-resources/
