// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type CertificateStatus_SDK string

const (
	CertificateStatus_SDK_EXPIRED              CertificateStatus_SDK = "EXPIRED"
	CertificateStatus_SDK_FAILED               CertificateStatus_SDK = "FAILED"
	CertificateStatus_SDK_INACTIVE             CertificateStatus_SDK = "INACTIVE"
	CertificateStatus_SDK_ISSUED               CertificateStatus_SDK = "ISSUED"
	CertificateStatus_SDK_PENDING_VALIDATION   CertificateStatus_SDK = "PENDING_VALIDATION"
	CertificateStatus_SDK_REVOKED              CertificateStatus_SDK = "REVOKED"
	CertificateStatus_SDK_VALIDATION_TIMED_OUT CertificateStatus_SDK = "VALIDATION_TIMED_OUT"
)

type CertificateTransparencyLoggingPreference string

const (
	CertificateTransparencyLoggingPreference_DISABLED CertificateTransparencyLoggingPreference = "DISABLED"
	CertificateTransparencyLoggingPreference_ENABLED  CertificateTransparencyLoggingPreference = "ENABLED"
)

type CertificateType string

const (
	CertificateType_AMAZON_ISSUED CertificateType = "AMAZON_ISSUED"
	CertificateType_IMPORTED      CertificateType = "IMPORTED"
	CertificateType_PRIVATE       CertificateType = "PRIVATE"
)

type DomainStatus string

const (
	DomainStatus_FAILED             DomainStatus = "FAILED"
	DomainStatus_PENDING_VALIDATION DomainStatus = "PENDING_VALIDATION"
	DomainStatus_SUCCESS            DomainStatus = "SUCCESS"
)

type ExtendedKeyUsageName string

const (
	ExtendedKeyUsageName_ANY                           ExtendedKeyUsageName = "ANY"
	ExtendedKeyUsageName_CODE_SIGNING                  ExtendedKeyUsageName = "CODE_SIGNING"
	ExtendedKeyUsageName_CUSTOM                        ExtendedKeyUsageName = "CUSTOM"
	ExtendedKeyUsageName_EMAIL_PROTECTION              ExtendedKeyUsageName = "EMAIL_PROTECTION"
	ExtendedKeyUsageName_IPSEC_END_SYSTEM              ExtendedKeyUsageName = "IPSEC_END_SYSTEM"
	ExtendedKeyUsageName_IPSEC_TUNNEL                  ExtendedKeyUsageName = "IPSEC_TUNNEL"
	ExtendedKeyUsageName_IPSEC_USER                    ExtendedKeyUsageName = "IPSEC_USER"
	ExtendedKeyUsageName_NONE                          ExtendedKeyUsageName = "NONE"
	ExtendedKeyUsageName_OCSP_SIGNING                  ExtendedKeyUsageName = "OCSP_SIGNING"
	ExtendedKeyUsageName_TIME_STAMPING                 ExtendedKeyUsageName = "TIME_STAMPING"
	ExtendedKeyUsageName_TLS_WEB_CLIENT_AUTHENTICATION ExtendedKeyUsageName = "TLS_WEB_CLIENT_AUTHENTICATION"
	ExtendedKeyUsageName_TLS_WEB_SERVER_AUTHENTICATION ExtendedKeyUsageName = "TLS_WEB_SERVER_AUTHENTICATION"
)

type FailureReason string

const (
	FailureReason_ADDITIONAL_VERIFICATION_REQUIRED FailureReason = "ADDITIONAL_VERIFICATION_REQUIRED"
	FailureReason_CAA_ERROR                        FailureReason = "CAA_ERROR"
	FailureReason_DOMAIN_NOT_ALLOWED               FailureReason = "DOMAIN_NOT_ALLOWED"
	FailureReason_DOMAIN_VALIDATION_DENIED         FailureReason = "DOMAIN_VALIDATION_DENIED"
	FailureReason_INVALID_PUBLIC_DOMAIN            FailureReason = "INVALID_PUBLIC_DOMAIN"
	FailureReason_NO_AVAILABLE_CONTACTS            FailureReason = "NO_AVAILABLE_CONTACTS"
	FailureReason_OTHER                            FailureReason = "OTHER"
	FailureReason_PCA_ACCESS_DENIED                FailureReason = "PCA_ACCESS_DENIED"
	FailureReason_PCA_INVALID_ARGS                 FailureReason = "PCA_INVALID_ARGS"
	FailureReason_PCA_INVALID_ARN                  FailureReason = "PCA_INVALID_ARN"
	FailureReason_PCA_INVALID_DURATION             FailureReason = "PCA_INVALID_DURATION"
	FailureReason_PCA_INVALID_STATE                FailureReason = "PCA_INVALID_STATE"
	FailureReason_PCA_LIMIT_EXCEEDED               FailureReason = "PCA_LIMIT_EXCEEDED"
	FailureReason_PCA_NAME_CONSTRAINTS_VALIDATION  FailureReason = "PCA_NAME_CONSTRAINTS_VALIDATION"
	FailureReason_PCA_REQUEST_FAILED               FailureReason = "PCA_REQUEST_FAILED"
	FailureReason_PCA_RESOURCE_NOT_FOUND           FailureReason = "PCA_RESOURCE_NOT_FOUND"
	FailureReason_SLR_NOT_FOUND                    FailureReason = "SLR_NOT_FOUND"
)

type KeyAlgorithm string

const (
	KeyAlgorithm_EC_prime256v1 KeyAlgorithm = "EC_prime256v1"
	KeyAlgorithm_EC_secp384r1  KeyAlgorithm = "EC_secp384r1"
	KeyAlgorithm_EC_secp521r1  KeyAlgorithm = "EC_secp521r1"
	KeyAlgorithm_RSA_1024      KeyAlgorithm = "RSA_1024"
	KeyAlgorithm_RSA_2048      KeyAlgorithm = "RSA_2048"
	KeyAlgorithm_RSA_3072      KeyAlgorithm = "RSA_3072"
	KeyAlgorithm_RSA_4096      KeyAlgorithm = "RSA_4096"
)

type KeyUsageName string

const (
	KeyUsageName_ANY                 KeyUsageName = "ANY"
	KeyUsageName_CERTIFICATE_SIGNING KeyUsageName = "CERTIFICATE_SIGNING"
	KeyUsageName_CRL_SIGNING         KeyUsageName = "CRL_SIGNING"
	KeyUsageName_CUSTOM              KeyUsageName = "CUSTOM"
	KeyUsageName_DATA_ENCIPHERMENT   KeyUsageName = "DATA_ENCIPHERMENT"
	KeyUsageName_DECIPHER_ONLY       KeyUsageName = "DECIPHER_ONLY"
	KeyUsageName_DIGITAL_SIGNATURE   KeyUsageName = "DIGITAL_SIGNATURE"
	KeyUsageName_ENCIPHER_ONLY       KeyUsageName = "ENCIPHER_ONLY"
	KeyUsageName_KEY_AGREEMENT       KeyUsageName = "KEY_AGREEMENT"
	KeyUsageName_KEY_ENCIPHERMENT    KeyUsageName = "KEY_ENCIPHERMENT"
	KeyUsageName_NON_REPUDIATION     KeyUsageName = "NON_REPUDIATION"
)

type RecordType string

const (
	RecordType_CNAME RecordType = "CNAME"
)

type RenewalEligibility string

const (
	RenewalEligibility_ELIGIBLE   RenewalEligibility = "ELIGIBLE"
	RenewalEligibility_INELIGIBLE RenewalEligibility = "INELIGIBLE"
)

type RenewalStatus string

const (
	RenewalStatus_FAILED               RenewalStatus = "FAILED"
	RenewalStatus_PENDING_AUTO_RENEWAL RenewalStatus = "PENDING_AUTO_RENEWAL"
	RenewalStatus_PENDING_VALIDATION   RenewalStatus = "PENDING_VALIDATION"
	RenewalStatus_SUCCESS              RenewalStatus = "SUCCESS"
)

type RevocationReason string

const (
	RevocationReason_AFFILIATION_CHANGED    RevocationReason = "AFFILIATION_CHANGED"
	RevocationReason_A_A_COMPROMISE         RevocationReason = "A_A_COMPROMISE"
	RevocationReason_CA_COMPROMISE          RevocationReason = "CA_COMPROMISE"
	RevocationReason_CERTIFICATE_HOLD       RevocationReason = "CERTIFICATE_HOLD"
	RevocationReason_CESSATION_OF_OPERATION RevocationReason = "CESSATION_OF_OPERATION"
	RevocationReason_KEY_COMPROMISE         RevocationReason = "KEY_COMPROMISE"
	RevocationReason_PRIVILEGE_WITHDRAWN    RevocationReason = "PRIVILEGE_WITHDRAWN"
	RevocationReason_REMOVE_FROM_CRL        RevocationReason = "REMOVE_FROM_CRL"
	RevocationReason_SUPERCEDED             RevocationReason = "SUPERCEDED"
	RevocationReason_UNSPECIFIED            RevocationReason = "UNSPECIFIED"
)

type SortBy string

const (
	SortBy_CREATED_AT SortBy = "CREATED_AT"
)

type SortOrder string

const (
	SortOrder_ASCENDING  SortOrder = "ASCENDING"
	SortOrder_DESCENDING SortOrder = "DESCENDING"
)

type ValidationMethod string

const (
	ValidationMethod_DNS   ValidationMethod = "DNS"
	ValidationMethod_EMAIL ValidationMethod = "EMAIL"
)
