//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMCertificateMetadata) DeepCopyInto(out *ACMCertificateMetadata) {
	*out = *in
	if in.AcmeAccountID != nil {
		in, out := &in.AcmeAccountID, &out.AcmeAccountID
		*out = new(string)
		**out = **in
	}
	if in.AcmeEndpointARN != nil {
		in, out := &in.AcmeEndpointARN, &out.AcmeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.CertificateKeyPairOrigin != nil {
		in, out := &in.CertificateKeyPairOrigin, &out.CertificateKeyPairOrigin
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ExportOption != nil {
		in, out := &in.ExportOption, &out.ExportOption
		*out = new(string)
		**out = **in
	}
	if in.Exported != nil {
		in, out := &in.Exported, &out.Exported
		*out = new(bool)
		**out = **in
	}
	if in.ImportedAt != nil {
		in, out := &in.ImportedAt, &out.ImportedAt
		*out = (*in).DeepCopy()
	}
	if in.InUse != nil {
		in, out := &in.InUse, &out.InUse
		*out = new(bool)
		**out = **in
	}
	if in.IssuedAt != nil {
		in, out := &in.IssuedAt, &out.IssuedAt
		*out = (*in).DeepCopy()
	}
	if in.ManagedBy != nil {
		in, out := &in.ManagedBy, &out.ManagedBy
		*out = new(string)
		**out = **in
	}
	if in.RenewalEligibility != nil {
		in, out := &in.RenewalEligibility, &out.RenewalEligibility
		*out = new(string)
		**out = **in
	}
	if in.RenewalStatus != nil {
		in, out := &in.RenewalStatus, &out.RenewalStatus
		*out = new(string)
		**out = **in
	}
	if in.RevokedAt != nil {
		in, out := &in.RevokedAt, &out.RevokedAt
		*out = (*in).DeepCopy()
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.ValidationMethod != nil {
		in, out := &in.ValidationMethod, &out.ValidationMethod
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMCertificateMetadata.
func (in *ACMCertificateMetadata) DeepCopy() *ACMCertificateMetadata {
	if in == nil {
		return nil
	}
	out := new(ACMCertificateMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMCertificateMetadataFilter) DeepCopyInto(out *ACMCertificateMetadataFilter) {
	*out = *in
	if in.AcmeAccountID != nil {
		in, out := &in.AcmeAccountID, &out.AcmeAccountID
		*out = new(string)
		**out = **in
	}
	if in.AcmeEndpointARN != nil {
		in, out := &in.AcmeEndpointARN, &out.AcmeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.CertificateKeyPairOrigin != nil {
		in, out := &in.CertificateKeyPairOrigin, &out.CertificateKeyPairOrigin
		*out = new(string)
		**out = **in
	}
	if in.ExportOption != nil {
		in, out := &in.ExportOption, &out.ExportOption
		*out = new(string)
		**out = **in
	}
	if in.Exported != nil {
		in, out := &in.Exported, &out.Exported
		*out = new(bool)
		**out = **in
	}
	if in.InUse != nil {
		in, out := &in.InUse, &out.InUse
		*out = new(bool)
		**out = **in
	}
	if in.ManagedBy != nil {
		in, out := &in.ManagedBy, &out.ManagedBy
		*out = new(string)
		**out = **in
	}
	if in.RenewalStatus != nil {
		in, out := &in.RenewalStatus, &out.RenewalStatus
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.ValidationMethod != nil {
		in, out := &in.ValidationMethod, &out.ValidationMethod
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMCertificateMetadataFilter.
func (in *ACMCertificateMetadataFilter) DeepCopy() *ACMCertificateMetadataFilter {
	if in == nil {
		return nil
	}
	out := new(ACMCertificateMetadataFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeAccount) DeepCopyInto(out *AcmeAccount) {
	*out = *in
	if in.AccountURL != nil {
		in, out := &in.AccountURL, &out.AccountURL
		*out = new(string)
		**out = **in
	}
	if in.AcmeExternalAccountBindingARN != nil {
		in, out := &in.AcmeExternalAccountBindingARN, &out.AcmeExternalAccountBindingARN
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.PublicKeyThumbprint != nil {
		in, out := &in.PublicKeyThumbprint, &out.PublicKeyThumbprint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeAccount.
func (in *AcmeAccount) DeepCopy() *AcmeAccount {
	if in == nil {
		return nil
	}
	out := new(AcmeAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeAccountSummary) DeepCopyInto(out *AcmeAccountSummary) {
	*out = *in
	if in.AccountURL != nil {
		in, out := &in.AccountURL, &out.AccountURL
		*out = new(string)
		**out = **in
	}
	if in.AcmeExternalAccountBindingARN != nil {
		in, out := &in.AcmeExternalAccountBindingARN, &out.AcmeExternalAccountBindingARN
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.PublicKeyThumbprint != nil {
		in, out := &in.PublicKeyThumbprint, &out.PublicKeyThumbprint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeAccountSummary.
func (in *AcmeAccountSummary) DeepCopy() *AcmeAccountSummary {
	if in == nil {
		return nil
	}
	out := new(AcmeAccountSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeDomainValidation) DeepCopyInto(out *AcmeDomainValidation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeDomainValidation.
func (in *AcmeDomainValidation) DeepCopy() *AcmeDomainValidation {
	if in == nil {
		return nil
	}
	out := new(AcmeDomainValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcmeDomainValidation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeDomainValidationList) DeepCopyInto(out *AcmeDomainValidationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcmeDomainValidation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeDomainValidationList.
func (in *AcmeDomainValidationList) DeepCopy() *AcmeDomainValidationList {
	if in == nil {
		return nil
	}
	out := new(AcmeDomainValidationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcmeDomainValidationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeDomainValidationSpec) DeepCopyInto(out *AcmeDomainValidationSpec) {
	*out = *in
	if in.AcmeEndpointARN != nil {
		in, out := &in.AcmeEndpointARN, &out.AcmeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.AcmeEndpointRef != nil {
		in, out := &in.AcmeEndpointRef, &out.AcmeEndpointRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.DomainName != nil {
		in, out := &in.DomainName, &out.DomainName
		*out = new(string)
		**out = **in
	}
	if in.PrevalidationOptions != nil {
		in, out := &in.PrevalidationOptions, &out.PrevalidationOptions
		*out = new(PrevalidationOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeDomainValidationSpec.
func (in *AcmeDomainValidationSpec) DeepCopy() *AcmeDomainValidationSpec {
	if in == nil {
		return nil
	}
	out := new(AcmeDomainValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeDomainValidationStatus) DeepCopyInto(out *AcmeDomainValidationStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.FailureDetails != nil {
		in, out := &in.FailureDetails, &out.FailureDetails
		*out = new(FailureDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.PrevalidationDetails != nil {
		in, out := &in.PrevalidationDetails, &out.PrevalidationDetails
		*out = new(PrevalidationDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.PrevalidationType != nil {
		in, out := &in.PrevalidationType, &out.PrevalidationType
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeDomainValidationStatus.
func (in *AcmeDomainValidationStatus) DeepCopy() *AcmeDomainValidationStatus {
	if in == nil {
		return nil
	}
	out := new(AcmeDomainValidationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeDomainValidationSummary) DeepCopyInto(out *AcmeDomainValidationSummary) {
	*out = *in
	if in.AcmeDomainValidationARN != nil {
		in, out := &in.AcmeDomainValidationARN, &out.AcmeDomainValidationARN
		*out = new(string)
		**out = **in
	}
	if in.AcmeEndpointARN != nil {
		in, out := &in.AcmeEndpointARN, &out.AcmeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.DomainName != nil {
		in, out := &in.DomainName, &out.DomainName
		*out = new(string)
		**out = **in
	}
	if in.FailureDetails != nil {
		in, out := &in.FailureDetails, &out.FailureDetails
		*out = new(FailureDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.PrevalidationDetails != nil {
		in, out := &in.PrevalidationDetails, &out.PrevalidationDetails
		*out = new(PrevalidationDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.PrevalidationType != nil {
		in, out := &in.PrevalidationType, &out.PrevalidationType
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeDomainValidationSummary.
func (in *AcmeDomainValidationSummary) DeepCopy() *AcmeDomainValidationSummary {
	if in == nil {
		return nil
	}
	out := new(AcmeDomainValidationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeDomainValidation_SDK) DeepCopyInto(out *AcmeDomainValidation_SDK) {
	*out = *in
	if in.AcmeDomainValidationARN != nil {
		in, out := &in.AcmeDomainValidationARN, &out.AcmeDomainValidationARN
		*out = new(string)
		**out = **in
	}
	if in.AcmeEndpointARN != nil {
		in, out := &in.AcmeEndpointARN, &out.AcmeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.DomainName != nil {
		in, out := &in.DomainName, &out.DomainName
		*out = new(string)
		**out = **in
	}
	if in.FailureDetails != nil {
		in, out := &in.FailureDetails, &out.FailureDetails
		*out = new(FailureDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.PrevalidationDetails != nil {
		in, out := &in.PrevalidationDetails, &out.PrevalidationDetails
		*out = new(PrevalidationDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.PrevalidationType != nil {
		in, out := &in.PrevalidationType, &out.PrevalidationType
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeDomainValidation_SDK.
func (in *AcmeDomainValidation_SDK) DeepCopy() *AcmeDomainValidation_SDK {
	if in == nil {
		return nil
	}
	out := new(AcmeDomainValidation_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeEndpoint) DeepCopyInto(out *AcmeEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeEndpoint.
func (in *AcmeEndpoint) DeepCopy() *AcmeEndpoint {
	if in == nil {
		return nil
	}
	out := new(AcmeEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcmeEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeEndpointList) DeepCopyInto(out *AcmeEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcmeEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeEndpointList.
func (in *AcmeEndpointList) DeepCopy() *AcmeEndpointList {
	if in == nil {
		return nil
	}
	out := new(AcmeEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcmeEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeEndpointSpec) DeepCopyInto(out *AcmeEndpointSpec) {
	*out = *in
	if in.AuthorizationBehavior != nil {
		in, out := &in.AuthorizationBehavior, &out.AuthorizationBehavior
		*out = new(string)
		**out = **in
	}
	if in.CertificateAuthority != nil {
		in, out := &in.CertificateAuthority, &out.CertificateAuthority
		*out = new(CertificateAuthority)
		(*in).DeepCopyInto(*out)
	}
	if in.CertificateTags != nil {
		in, out := &in.CertificateTags, &out.CertificateTags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Contact != nil {
		in, out := &in.Contact, &out.Contact
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeEndpointSpec.
func (in *AcmeEndpointSpec) DeepCopy() *AcmeEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(AcmeEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeEndpointStatus) DeepCopyInto(out *AcmeEndpointStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.AcmeEndpointARN != nil {
		in, out := &in.AcmeEndpointARN, &out.AcmeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.EndpointURL != nil {
		in, out := &in.EndpointURL, &out.EndpointURL
		*out = new(string)
		**out = **in
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeEndpointStatus.
func (in *AcmeEndpointStatus) DeepCopy() *AcmeEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(AcmeEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeEndpointSummary) DeepCopyInto(out *AcmeEndpointSummary) {
	*out = *in
	if in.AcmeEndpointARN != nil {
		in, out := &in.AcmeEndpointARN, &out.AcmeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationBehavior != nil {
		in, out := &in.AuthorizationBehavior, &out.AuthorizationBehavior
		*out = new(string)
		**out = **in
	}
	if in.CertificateAuthority != nil {
		in, out := &in.CertificateAuthority, &out.CertificateAuthority
		*out = new(CertificateAuthority)
		(*in).DeepCopyInto(*out)
	}
	if in.CertificateTags != nil {
		in, out := &in.CertificateTags, &out.CertificateTags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Contact != nil {
		in, out := &in.Contact, &out.Contact
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.EndpointURL != nil {
		in, out := &in.EndpointURL, &out.EndpointURL
		*out = new(string)
		**out = **in
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeEndpointSummary.
func (in *AcmeEndpointSummary) DeepCopy() *AcmeEndpointSummary {
	if in == nil {
		return nil
	}
	out := new(AcmeEndpointSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeEndpoint_SDK) DeepCopyInto(out *AcmeEndpoint_SDK) {
	*out = *in
	if in.AcmeEndpointARN != nil {
		in, out := &in.AcmeEndpointARN, &out.AcmeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationBehavior != nil {
		in, out := &in.AuthorizationBehavior, &out.AuthorizationBehavior
		*out = new(string)
		**out = **in
	}
	if in.CertificateAuthority != nil {
		in, out := &in.CertificateAuthority, &out.CertificateAuthority
		*out = new(CertificateAuthority)
		(*in).DeepCopyInto(*out)
	}
	if in.CertificateTags != nil {
		in, out := &in.CertificateTags, &out.CertificateTags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Contact != nil {
		in, out := &in.Contact, &out.Contact
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.EndpointURL != nil {
		in, out := &in.EndpointURL, &out.EndpointURL
		*out = new(string)
		**out = **in
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeEndpoint_SDK.
func (in *AcmeEndpoint_SDK) DeepCopy() *AcmeEndpoint_SDK {
	if in == nil {
		return nil
	}
	out := new(AcmeEndpoint_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeExternalAccountBinding) DeepCopyInto(out *AcmeExternalAccountBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeExternalAccountBinding.
func (in *AcmeExternalAccountBinding) DeepCopy() *AcmeExternalAccountBinding {
	if in == nil {
		return nil
	}
	out := new(AcmeExternalAccountBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcmeExternalAccountBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeExternalAccountBindingList) DeepCopyInto(out *AcmeExternalAccountBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcmeExternalAccountBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeExternalAccountBindingList.
func (in *AcmeExternalAccountBindingList) DeepCopy() *AcmeExternalAccountBindingList {
	if in == nil {
		return nil
	}
	out := new(AcmeExternalAccountBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcmeExternalAccountBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeExternalAccountBindingSpec) DeepCopyInto(out *AcmeExternalAccountBindingSpec) {
	*out = *in
	if in.AcmeEndpointARN != nil {
		in, out := &in.AcmeEndpointARN, &out.AcmeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.AcmeEndpointRef != nil {
		in, out := &in.AcmeEndpointRef, &out.AcmeEndpointRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialsOutput != nil {
		in, out := &in.CredentialsOutput, &out.CredentialsOutput
		*out = new(corev1alpha1.SecretKeyReference)
		**out = **in
	}
	if in.Expiration != nil {
		in, out := &in.Expiration, &out.Expiration
		*out = new(Expiration)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
	if in.RoleRef != nil {
		in, out := &in.RoleRef, &out.RoleRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeExternalAccountBindingSpec.
func (in *AcmeExternalAccountBindingSpec) DeepCopy() *AcmeExternalAccountBindingSpec {
	if in == nil {
		return nil
	}
	out := new(AcmeExternalAccountBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeExternalAccountBindingStatus) DeepCopyInto(out *AcmeExternalAccountBindingStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
	if in.LastUsedAt != nil {
		in, out := &in.LastUsedAt, &out.LastUsedAt
		*out = (*in).DeepCopy()
	}
	if in.RevokedAt != nil {
		in, out := &in.RevokedAt, &out.RevokedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeExternalAccountBindingStatus.
func (in *AcmeExternalAccountBindingStatus) DeepCopy() *AcmeExternalAccountBindingStatus {
	if in == nil {
		return nil
	}
	out := new(AcmeExternalAccountBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeExternalAccountBindingSummary) DeepCopyInto(out *AcmeExternalAccountBindingSummary) {
	*out = *in
	if in.AcmeEndpointARN != nil {
		in, out := &in.AcmeEndpointARN, &out.AcmeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.AcmeExternalAccountBindingARN != nil {
		in, out := &in.AcmeExternalAccountBindingARN, &out.AcmeExternalAccountBindingARN
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.LastUsedAt != nil {
		in, out := &in.LastUsedAt, &out.LastUsedAt
		*out = (*in).DeepCopy()
	}
	if in.RevokedAt != nil {
		in, out := &in.RevokedAt, &out.RevokedAt
		*out = (*in).DeepCopy()
	}
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeExternalAccountBindingSummary.
func (in *AcmeExternalAccountBindingSummary) DeepCopy() *AcmeExternalAccountBindingSummary {
	if in == nil {
		return nil
	}
	out := new(AcmeExternalAccountBindingSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeExternalAccountBinding_SDK) DeepCopyInto(out *AcmeExternalAccountBinding_SDK) {
	*out = *in
	if in.AcmeEndpointARN != nil {
		in, out := &in.AcmeEndpointARN, &out.AcmeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.AcmeExternalAccountBindingARN != nil {
		in, out := &in.AcmeExternalAccountBindingARN, &out.AcmeExternalAccountBindingARN
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.LastUsedAt != nil {
		in, out := &in.LastUsedAt, &out.LastUsedAt
		*out = (*in).DeepCopy()
	}
	if in.RevokedAt != nil {
		in, out := &in.RevokedAt, &out.RevokedAt
		*out = (*in).DeepCopy()
	}
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeExternalAccountBinding_SDK.
func (in *AcmeExternalAccountBinding_SDK) DeepCopy() *AcmeExternalAccountBinding_SDK {
	if in == nil {
		return nil
	}
	out := new(AcmeExternalAccountBinding_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Certificate) DeepCopyInto(out *Certificate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Certificate.
func (in *Certificate) DeepCopy() *Certificate {
	if in == nil {
		return nil
	}
	out := new(Certificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Certificate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateAuthority) DeepCopyInto(out *CertificateAuthority) {
	*out = *in
	if in.PublicCertificateAuthority != nil {
		in, out := &in.PublicCertificateAuthority, &out.PublicCertificateAuthority
		*out = new(PublicCertificateAuthority)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateAuthority.
func (in *CertificateAuthority) DeepCopy() *CertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(CertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateDetail) DeepCopyInto(out *CertificateDetail) {
	*out = *in
	if in.AcmeAccountID != nil {
		in, out := &in.AcmeAccountID, &out.AcmeAccountID
		*out = new(string)
		**out = **in
	}
	if in.AcmeEndpointARN != nil {
		in, out := &in.AcmeEndpointARN, &out.AcmeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.CertificateARN != nil {
		in, out := &in.CertificateARN, &out.CertificateARN
		*out = new(string)
		**out = **in
	}
	if in.CertificateAuthorityARN != nil {
		in, out := &in.CertificateAuthorityARN, &out.CertificateAuthorityARN
		*out = new(string)
		**out = **in
	}
	if in.CertificateKeyPairOrigin != nil {
		in, out := &in.CertificateKeyPairOrigin, &out.CertificateKeyPairOrigin
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.DomainName != nil {
		in, out := &in.DomainName, &out.DomainName
		*out = new(string)
		**out = **in
	}
	if in.DomainValidationOptions != nil {
		in, out := &in.DomainValidationOptions, &out.DomainValidationOptions
		*out = make([]*DomainValidation, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DomainValidation)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ExtendedKeyUsages != nil {
		in, out := &in.ExtendedKeyUsages, &out.ExtendedKeyUsages
		*out = make([]*ExtendedKeyUsage, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ExtendedKeyUsage)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.ImportedAt != nil {
		in, out := &in.ImportedAt, &out.ImportedAt
		*out = (*in).DeepCopy()
	}
	if in.InUseBy != nil {
		in, out := &in.InUseBy, &out.InUseBy
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IssuedAt != nil {
		in, out := &in.IssuedAt, &out.IssuedAt
		*out = (*in).DeepCopy()
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.KeyAlgorithm != nil {
		in, out := &in.KeyAlgorithm, &out.KeyAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.KeyUsages != nil {
		in, out := &in.KeyUsages, &out.KeyUsages
		*out = make([]*KeyUsage, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(KeyUsage)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ManagedBy != nil {
		in, out := &in.ManagedBy, &out.ManagedBy
		*out = new(string)
		**out = **in
	}
	if in.NotAfter != nil {
		in, out := &in.NotAfter, &out.NotAfter
		*out = (*in).DeepCopy()
	}
	if in.NotBefore != nil {
		in, out := &in.NotBefore, &out.NotBefore
		*out = (*in).DeepCopy()
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(CertificateOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.RenewalEligibility != nil {
		in, out := &in.RenewalEligibility, &out.RenewalEligibility
		*out = new(string)
		**out = **in
	}
	if in.RenewalSummary != nil {
		in, out := &in.RenewalSummary, &out.RenewalSummary
		*out = new(RenewalSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.RevocationReason != nil {
		in, out := &in.RevocationReason, &out.RevocationReason
		*out = new(string)
		**out = **in
	}
	if in.RevokedAt != nil {
		in, out := &in.RevokedAt, &out.RevokedAt
		*out = (*in).DeepCopy()
	}
	if in.Serial != nil {
		in, out := &in.Serial, &out.Serial
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.SubjectAlternativeNames != nil {
		in, out := &in.SubjectAlternativeNames, &out.SubjectAlternativeNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateDetail.
func (in *CertificateDetail) DeepCopy() *CertificateDetail {
	if in == nil {
		return nil
	}
	out := new(CertificateDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateFilter) DeepCopyInto(out *CertificateFilter) {
	*out = *in
	if in.CertificateARN != nil {
		in, out := &in.CertificateARN, &out.CertificateARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateFilter.
func (in *CertificateFilter) DeepCopy() *CertificateFilter {
	if in == nil {
		return nil
	}
	out := new(CertificateFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateList) DeepCopyInto(out *CertificateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Certificate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateList.
func (in *CertificateList) DeepCopy() *CertificateList {
	if in == nil {
		return nil
	}
	out := new(CertificateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateOptions) DeepCopyInto(out *CertificateOptions) {
	*out = *in
	if in.CertificateTransparencyLoggingPreference != nil {
		in, out := &in.CertificateTransparencyLoggingPreference, &out.CertificateTransparencyLoggingPreference
		*out = new(string)
		**out = **in
	}
	if in.Export != nil {
		in, out := &in.Export, &out.Export
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateOptions.
func (in *CertificateOptions) DeepCopy() *CertificateOptions {
	if in == nil {
		return nil
	}
	out := new(CertificateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSearchResult) DeepCopyInto(out *CertificateSearchResult) {
	*out = *in
	if in.CertificateARN != nil {
		in, out := &in.CertificateARN, &out.CertificateARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSearchResult.
func (in *CertificateSearchResult) DeepCopy() *CertificateSearchResult {
	if in == nil {
		return nil
	}
	out := new(CertificateSearchResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpec) DeepCopyInto(out *CertificateSpec) {
	*out = *in
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(corev1alpha1.SecretKeyReference)
		**out = **in
	}
	if in.CertificateARN != nil {
		in, out := &in.CertificateARN, &out.CertificateARN
		*out = new(string)
		**out = **in
	}
	if in.CertificateAuthorityARN != nil {
		in, out := &in.CertificateAuthorityARN, &out.CertificateAuthorityARN
		*out = new(string)
		**out = **in
	}
	if in.CertificateAuthorityRef != nil {
		in, out := &in.CertificateAuthorityRef, &out.CertificateAuthorityRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.CertificateChain != nil {
		in, out := &in.CertificateChain, &out.CertificateChain
		*out = new(corev1alpha1.SecretKeyReference)
		**out = **in
	}
	if in.DomainName != nil {
		in, out := &in.DomainName, &out.DomainName
		*out = new(string)
		**out = **in
	}
	if in.DomainValidationOptions != nil {
		in, out := &in.DomainValidationOptions, &out.DomainValidationOptions
		*out = make([]*DomainValidationOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DomainValidationOption)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ExportTo != nil {
		in, out := &in.ExportTo, &out.ExportTo
		*out = new(corev1alpha1.SecretKeyReference)
		**out = **in
	}
	if in.ImportFrom != nil {
		in, out := &in.ImportFrom, &out.ImportFrom
		*out = new(corev1alpha1.SecretReference)
		**out = **in
	}
	if in.KeyAlgorithm != nil {
		in, out := &in.KeyAlgorithm, &out.KeyAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.ManagedBy != nil {
		in, out := &in.ManagedBy, &out.ManagedBy
		*out = new(string)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(CertificateOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = new(corev1alpha1.SecretKeyReference)
		**out = **in
	}
	if in.SubjectAlternativeNames != nil {
		in, out := &in.SubjectAlternativeNames, &out.SubjectAlternativeNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpec.
func (in *CertificateSpec) DeepCopy() *CertificateSpec {
	if in == nil {
		return nil
	}
	out := new(CertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateStatus) DeepCopyInto(out *CertificateStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.DomainValidations != nil {
		in, out := &in.DomainValidations, &out.DomainValidations
		*out = make([]*DomainValidation, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DomainValidation)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ExtendedKeyUsages != nil {
		in, out := &in.ExtendedKeyUsages, &out.ExtendedKeyUsages
		*out = make([]*ExtendedKeyUsage, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ExtendedKeyUsage)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.ImportedAt != nil {
		in, out := &in.ImportedAt, &out.ImportedAt
		*out = (*in).DeepCopy()
	}
	if in.InUseBy != nil {
		in, out := &in.InUseBy, &out.InUseBy
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IssuedAt != nil {
		in, out := &in.IssuedAt, &out.IssuedAt
		*out = (*in).DeepCopy()
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.KeyUsages != nil {
		in, out := &in.KeyUsages, &out.KeyUsages
		*out = make([]*KeyUsage, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(KeyUsage)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NotAfter != nil {
		in, out := &in.NotAfter, &out.NotAfter
		*out = (*in).DeepCopy()
	}
	if in.NotBefore != nil {
		in, out := &in.NotBefore, &out.NotBefore
		*out = (*in).DeepCopy()
	}
	if in.RenewalEligibility != nil {
		in, out := &in.RenewalEligibility, &out.RenewalEligibility
		*out = new(string)
		**out = **in
	}
	if in.RenewalSummary != nil {
		in, out := &in.RenewalSummary, &out.RenewalSummary
		*out = new(RenewalSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.RevocationReason != nil {
		in, out := &in.RevocationReason, &out.RevocationReason
		*out = new(string)
		**out = **in
	}
	if in.RevokedAt != nil {
		in, out := &in.RevokedAt, &out.RevokedAt
		*out = (*in).DeepCopy()
	}
	if in.Serial != nil {
		in, out := &in.Serial, &out.Serial
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateStatus.
func (in *CertificateStatus) DeepCopy() *CertificateStatus {
	if in == nil {
		return nil
	}
	out := new(CertificateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSummary) DeepCopyInto(out *CertificateSummary) {
	*out = *in
	if in.CertificateARN != nil {
		in, out := &in.CertificateARN, &out.CertificateARN
		*out = new(string)
		**out = **in
	}
	if in.CertificateKeyPairOrigin != nil {
		in, out := &in.CertificateKeyPairOrigin, &out.CertificateKeyPairOrigin
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.DomainName != nil {
		in, out := &in.DomainName, &out.DomainName
		*out = new(string)
		**out = **in
	}
	if in.ExportOption != nil {
		in, out := &in.ExportOption, &out.ExportOption
		*out = new(string)
		**out = **in
	}
	if in.Exported != nil {
		in, out := &in.Exported, &out.Exported
		*out = new(bool)
		**out = **in
	}
	if in.ExtendedKeyUsages != nil {
		in, out := &in.ExtendedKeyUsages, &out.ExtendedKeyUsages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.HasAdditionalSubjectAlternativeNames != nil {
		in, out := &in.HasAdditionalSubjectAlternativeNames, &out.HasAdditionalSubjectAlternativeNames
		*out = new(bool)
		**out = **in
	}
	if in.ImportedAt != nil {
		in, out := &in.ImportedAt, &out.ImportedAt
		*out = (*in).DeepCopy()
	}
	if in.InUse != nil {
		in, out := &in.InUse, &out.InUse
		*out = new(bool)
		**out = **in
	}
	if in.IssuedAt != nil {
		in, out := &in.IssuedAt, &out.IssuedAt
		*out = (*in).DeepCopy()
	}
	if in.KeyAlgorithm != nil {
		in, out := &in.KeyAlgorithm, &out.KeyAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.KeyUsages != nil {
		in, out := &in.KeyUsages, &out.KeyUsages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ManagedBy != nil {
		in, out := &in.ManagedBy, &out.ManagedBy
		*out = new(string)
		**out = **in
	}
	if in.NotAfter != nil {
		in, out := &in.NotAfter, &out.NotAfter
		*out = (*in).DeepCopy()
	}
	if in.NotBefore != nil {
		in, out := &in.NotBefore, &out.NotBefore
		*out = (*in).DeepCopy()
	}
	if in.RenewalEligibility != nil {
		in, out := &in.RenewalEligibility, &out.RenewalEligibility
		*out = new(string)
		**out = **in
	}
	if in.RevokedAt != nil {
		in, out := &in.RevokedAt, &out.RevokedAt
		*out = (*in).DeepCopy()
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.SubjectAlternativeNameSummaries != nil {
		in, out := &in.SubjectAlternativeNameSummaries, &out.SubjectAlternativeNameSummaries
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSummary.
func (in *CertificateSummary) DeepCopy() *CertificateSummary {
	if in == nil {
		return nil
	}
	out := new(CertificateSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAttribute) DeepCopyInto(out *CustomAttribute) {
	*out = *in
	if in.ObjectIdentifier != nil {
		in, out := &in.ObjectIdentifier, &out.ObjectIdentifier
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAttribute.
func (in *CustomAttribute) DeepCopy() *CustomAttribute {
	if in == nil {
		return nil
	}
	out := new(CustomAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPrevalidationDetails) DeepCopyInto(out *DNSPrevalidationDetails) {
	*out = *in
	if in.DomainScope != nil {
		in, out := &in.DomainScope, &out.DomainScope
		*out = new(DomainScope)
		(*in).DeepCopyInto(*out)
	}
	if in.HostedZoneID != nil {
		in, out := &in.HostedZoneID, &out.HostedZoneID
		*out = new(string)
		**out = **in
	}
	if in.ResourceRecord != nil {
		in, out := &in.ResourceRecord, &out.ResourceRecord
		*out = new(ResourceRecord)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPrevalidationDetails.
func (in *DNSPrevalidationDetails) DeepCopy() *DNSPrevalidationDetails {
	if in == nil {
		return nil
	}
	out := new(DNSPrevalidationDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPrevalidationOptions) DeepCopyInto(out *DNSPrevalidationOptions) {
	*out = *in
	if in.DomainScope != nil {
		in, out := &in.DomainScope, &out.DomainScope
		*out = new(DomainScope)
		(*in).DeepCopyInto(*out)
	}
	if in.HostedZoneID != nil {
		in, out := &in.HostedZoneID, &out.HostedZoneID
		*out = new(string)
		**out = **in
	}
	if in.HostedZoneRef != nil {
		in, out := &in.HostedZoneRef, &out.HostedZoneRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPrevalidationOptions.
func (in *DNSPrevalidationOptions) DeepCopy() *DNSPrevalidationOptions {
	if in == nil {
		return nil
	}
	out := new(DNSPrevalidationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistinguishedName) DeepCopyInto(out *DistinguishedName) {
	*out = *in
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(string)
		**out = **in
	}
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = new(string)
		**out = **in
	}
	if in.DistinguishedNameQualifier != nil {
		in, out := &in.DistinguishedNameQualifier, &out.DistinguishedNameQualifier
		*out = new(string)
		**out = **in
	}
	if in.GenerationQualifier != nil {
		in, out := &in.GenerationQualifier, &out.GenerationQualifier
		*out = new(string)
		**out = **in
	}
	if in.GivenName != nil {
		in, out := &in.GivenName, &out.GivenName
		*out = new(string)
		**out = **in
	}
	if in.Initials != nil {
		in, out := &in.Initials, &out.Initials
		*out = new(string)
		**out = **in
	}
	if in.Locality != nil {
		in, out := &in.Locality, &out.Locality
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = new(string)
		**out = **in
	}
	if in.Pseudonym != nil {
		in, out := &in.Pseudonym, &out.Pseudonym
		*out = new(string)
		**out = **in
	}
	if in.SerialNumber != nil {
		in, out := &in.SerialNumber, &out.SerialNumber
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Surname != nil {
		in, out := &in.Surname, &out.Surname
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistinguishedName.
func (in *DistinguishedName) DeepCopy() *DistinguishedName {
	if in == nil {
		return nil
	}
	out := new(DistinguishedName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainScope) DeepCopyInto(out *DomainScope) {
	*out = *in
	if in.ExactDomain != nil {
		in, out := &in.ExactDomain, &out.ExactDomain
		*out = new(string)
		**out = **in
	}
	if in.Subdomains != nil {
		in, out := &in.Subdomains, &out.Subdomains
		*out = new(string)
		**out = **in
	}
	if in.Wildcards != nil {
		in, out := &in.Wildcards, &out.Wildcards
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainScope.
func (in *DomainScope) DeepCopy() *DomainScope {
	if in == nil {
		return nil
	}
	out := new(DomainScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainValidation) DeepCopyInto(out *DomainValidation) {
	*out = *in
	if in.DomainName != nil {
		in, out := &in.DomainName, &out.DomainName
		*out = new(string)
		**out = **in
	}
	if in.HTTPRedirect != nil {
		in, out := &in.HTTPRedirect, &out.HTTPRedirect
		*out = new(HTTPRedirect)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceRecord != nil {
		in, out := &in.ResourceRecord, &out.ResourceRecord
		*out = new(ResourceRecord)
		(*in).DeepCopyInto(*out)
	}
	if in.ValidationDomain != nil {
		in, out := &in.ValidationDomain, &out.ValidationDomain
		*out = new(string)
		**out = **in
	}
	if in.ValidationEmails != nil {
		in, out := &in.ValidationEmails, &out.ValidationEmails
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ValidationMethod != nil {
		in, out := &in.ValidationMethod, &out.ValidationMethod
		*out = new(string)
		**out = **in
	}
	if in.ValidationStatus != nil {
		in, out := &in.ValidationStatus, &out.ValidationStatus
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainValidation.
func (in *DomainValidation) DeepCopy() *DomainValidation {
	if in == nil {
		return nil
	}
	out := new(DomainValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainValidationOption) DeepCopyInto(out *DomainValidationOption) {
	*out = *in
	if in.DomainName != nil {
		in, out := &in.DomainName, &out.DomainName
		*out = new(string)
		**out = **in
	}
	if in.ValidationDomain != nil {
		in, out := &in.ValidationDomain, &out.ValidationDomain
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainValidationOption.
func (in *DomainValidationOption) DeepCopy() *DomainValidationOption {
	if in == nil {
		return nil
	}
	out := new(DomainValidationOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Expiration) DeepCopyInto(out *Expiration) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Expiration.
func (in *Expiration) DeepCopy() *Expiration {
	if in == nil {
		return nil
	}
	out := new(Expiration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtendedKeyUsage) DeepCopyInto(out *ExtendedKeyUsage) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OID != nil {
		in, out := &in.OID, &out.OID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtendedKeyUsage.
func (in *ExtendedKeyUsage) DeepCopy() *ExtendedKeyUsage {
	if in == nil {
		return nil
	}
	out := new(ExtendedKeyUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureDetails) DeepCopyInto(out *FailureDetails) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureDetails.
func (in *FailureDetails) DeepCopy() *FailureDetails {
	if in == nil {
		return nil
	}
	out := new(FailureDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Filters) DeepCopyInto(out *Filters) {
	*out = *in
	if in.ExportOption != nil {
		in, out := &in.ExportOption, &out.ExportOption
		*out = new(string)
		**out = **in
	}
	if in.ExtendedKeyUsage != nil {
		in, out := &in.ExtendedKeyUsage, &out.ExtendedKeyUsage
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.KeyTypes != nil {
		in, out := &in.KeyTypes, &out.KeyTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.KeyUsage != nil {
		in, out := &in.KeyUsage, &out.KeyUsage
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ManagedBy != nil {
		in, out := &in.ManagedBy, &out.ManagedBy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Filters.
func (in *Filters) DeepCopy() *Filters {
	if in == nil {
		return nil
	}
	out := new(Filters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralName) DeepCopyInto(out *GeneralName) {
	*out = *in
	if in.DNSName != nil {
		in, out := &in.DNSName, &out.DNSName
		*out = new(string)
		**out = **in
	}
	if in.IPAddress != nil {
		in, out := &in.IPAddress, &out.IPAddress
		*out = new(string)
		**out = **in
	}
	if in.RegisteredID != nil {
		in, out := &in.RegisteredID, &out.RegisteredID
		*out = new(string)
		**out = **in
	}
	if in.RFC822Name != nil {
		in, out := &in.RFC822Name, &out.RFC822Name
		*out = new(string)
		**out = **in
	}
	if in.UniformResourceIdentifier != nil {
		in, out := &in.UniformResourceIdentifier, &out.UniformResourceIdentifier
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralName.
func (in *GeneralName) DeepCopy() *GeneralName {
	if in == nil {
		return nil
	}
	out := new(GeneralName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRedirect) DeepCopyInto(out *HTTPRedirect) {
	*out = *in
	if in.RedirectFrom != nil {
		in, out := &in.RedirectFrom, &out.RedirectFrom
		*out = new(string)
		**out = **in
	}
	if in.RedirectTo != nil {
		in, out := &in.RedirectTo, &out.RedirectTo
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRedirect.
func (in *HTTPRedirect) DeepCopy() *HTTPRedirect {
	if in == nil {
		return nil
	}
	out := new(HTTPRedirect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyUsage) DeepCopyInto(out *KeyUsage) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyUsage.
func (in *KeyUsage) DeepCopy() *KeyUsage {
	if in == nil {
		return nil
	}
	out := new(KeyUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtherName) DeepCopyInto(out *OtherName) {
	*out = *in
	if in.ObjectIdentifier != nil {
		in, out := &in.ObjectIdentifier, &out.ObjectIdentifier
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtherName.
func (in *OtherName) DeepCopy() *OtherName {
	if in == nil {
		return nil
	}
	out := new(OtherName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrevalidationDetails) DeepCopyInto(out *PrevalidationDetails) {
	*out = *in
	if in.DNSPrevalidation != nil {
		in, out := &in.DNSPrevalidation, &out.DNSPrevalidation
		*out = new(DNSPrevalidationDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrevalidationDetails.
func (in *PrevalidationDetails) DeepCopy() *PrevalidationDetails {
	if in == nil {
		return nil
	}
	out := new(PrevalidationDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrevalidationOptions) DeepCopyInto(out *PrevalidationOptions) {
	*out = *in
	if in.DNSPrevalidation != nil {
		in, out := &in.DNSPrevalidation, &out.DNSPrevalidation
		*out = new(DNSPrevalidationOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrevalidationOptions.
func (in *PrevalidationOptions) DeepCopy() *PrevalidationOptions {
	if in == nil {
		return nil
	}
	out := new(PrevalidationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicCertificateAuthority) DeepCopyInto(out *PublicCertificateAuthority) {
	*out = *in
	if in.AllowedKeyAlgorithms != nil {
		in, out := &in.AllowedKeyAlgorithms, &out.AllowedKeyAlgorithms
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicCertificateAuthority.
func (in *PublicCertificateAuthority) DeepCopy() *PublicCertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(PublicCertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenewalSummary) DeepCopyInto(out *RenewalSummary) {
	*out = *in
	if in.DomainValidationOptions != nil {
		in, out := &in.DomainValidationOptions, &out.DomainValidationOptions
		*out = make([]*DomainValidation, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DomainValidation)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.RenewalStatus != nil {
		in, out := &in.RenewalStatus, &out.RenewalStatus
		*out = new(string)
		**out = **in
	}
	if in.RenewalStatusReason != nil {
		in, out := &in.RenewalStatusReason, &out.RenewalStatusReason
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenewalSummary.
func (in *RenewalSummary) DeepCopy() *RenewalSummary {
	if in == nil {
		return nil
	}
	out := new(RenewalSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRecord) DeepCopyInto(out *ResourceRecord) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRecord.
func (in *ResourceRecord) DeepCopy() *ResourceRecord {
	if in == nil {
		return nil
	}
	out := new(ResourceRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimestampRange) DeepCopyInto(out *TimestampRange) {
	*out = *in
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = (*in).DeepCopy()
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimestampRange.
func (in *TimestampRange) DeepCopy() *TimestampRange {
	if in == nil {
		return nil
	}
	out := new(TimestampRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *X509AttributeFilter) DeepCopyInto(out *X509AttributeFilter) {
	*out = *in
	if in.ExtendedKeyUsage != nil {
		in, out := &in.ExtendedKeyUsage, &out.ExtendedKeyUsage
		*out = new(string)
		**out = **in
	}
	if in.KeyAlgorithm != nil {
		in, out := &in.KeyAlgorithm, &out.KeyAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.KeyUsage != nil {
		in, out := &in.KeyUsage, &out.KeyUsage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new X509AttributeFilter.
func (in *X509AttributeFilter) DeepCopy() *X509AttributeFilter {
	if in == nil {
		return nil
	}
	out := new(X509AttributeFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *X509Attributes) DeepCopyInto(out *X509Attributes) {
	*out = *in
	if in.ExtendedKeyUsages != nil {
		in, out := &in.ExtendedKeyUsages, &out.ExtendedKeyUsages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.KeyAlgorithm != nil {
		in, out := &in.KeyAlgorithm, &out.KeyAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.KeyUsages != nil {
		in, out := &in.KeyUsages, &out.KeyUsages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NotAfter != nil {
		in, out := &in.NotAfter, &out.NotAfter
		*out = (*in).DeepCopy()
	}
	if in.NotBefore != nil {
		in, out := &in.NotBefore, &out.NotBefore
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new X509Attributes.
func (in *X509Attributes) DeepCopy() *X509Attributes {
	if in == nil {
		return nil
	}
	out := new(X509Attributes)
	in.DeepCopyInto(out)
	return out
}
