// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package certificate

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.CertificateARN, b.ko.Spec.CertificateARN) {
		delta.Add("Spec.CertificateARN", a.ko.Spec.CertificateARN, b.ko.Spec.CertificateARN)
	} else if a.ko.Spec.CertificateARN != nil && b.ko.Spec.CertificateARN != nil {
		if *a.ko.Spec.CertificateARN != *b.ko.Spec.CertificateARN {
			delta.Add("Spec.CertificateARN", a.ko.Spec.CertificateARN, b.ko.Spec.CertificateARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.CertificateAuthorityARN, b.ko.Spec.CertificateAuthorityARN) {
		delta.Add("Spec.CertificateAuthorityARN", a.ko.Spec.CertificateAuthorityARN, b.ko.Spec.CertificateAuthorityARN)
	} else if a.ko.Spec.CertificateAuthorityARN != nil && b.ko.Spec.CertificateAuthorityARN != nil {
		if *a.ko.Spec.CertificateAuthorityARN != *b.ko.Spec.CertificateAuthorityARN {
			delta.Add("Spec.CertificateAuthorityARN", a.ko.Spec.CertificateAuthorityARN, b.ko.Spec.CertificateAuthorityARN)
		}
	}
	if !reflect.DeepEqual(a.ko.Spec.CertificateAuthorityRef, b.ko.Spec.CertificateAuthorityRef) {
		delta.Add("Spec.CertificateAuthorityRef", a.ko.Spec.CertificateAuthorityRef, b.ko.Spec.CertificateAuthorityRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DomainName, b.ko.Spec.DomainName) {
		delta.Add("Spec.DomainName", a.ko.Spec.DomainName, b.ko.Spec.DomainName)
	} else if a.ko.Spec.DomainName != nil && b.ko.Spec.DomainName != nil {
		if *a.ko.Spec.DomainName != *b.ko.Spec.DomainName {
			delta.Add("Spec.DomainName", a.ko.Spec.DomainName, b.ko.Spec.DomainName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Options, b.ko.Spec.Options) {
		delta.Add("Spec.Options", a.ko.Spec.Options, b.ko.Spec.Options)
	} else if a.ko.Spec.Options != nil && b.ko.Spec.Options != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Options.CertificateTransparencyLoggingPreference, b.ko.Spec.Options.CertificateTransparencyLoggingPreference) {
			delta.Add("Spec.Options.CertificateTransparencyLoggingPreference", a.ko.Spec.Options.CertificateTransparencyLoggingPreference, b.ko.Spec.Options.CertificateTransparencyLoggingPreference)
		} else if a.ko.Spec.Options.CertificateTransparencyLoggingPreference != nil && b.ko.Spec.Options.CertificateTransparencyLoggingPreference != nil {
			if *a.ko.Spec.Options.CertificateTransparencyLoggingPreference != *b.ko.Spec.Options.CertificateTransparencyLoggingPreference {
				delta.Add("Spec.Options.CertificateTransparencyLoggingPreference", a.ko.Spec.Options.CertificateTransparencyLoggingPreference, b.ko.Spec.Options.CertificateTransparencyLoggingPreference)
			}
		}
	}
	if len(a.ko.Spec.SubjectAlternativeNames) != len(b.ko.Spec.SubjectAlternativeNames) {
		delta.Add("Spec.SubjectAlternativeNames", a.ko.Spec.SubjectAlternativeNames, b.ko.Spec.SubjectAlternativeNames)
	} else if len(a.ko.Spec.SubjectAlternativeNames) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.SubjectAlternativeNames, b.ko.Spec.SubjectAlternativeNames) {
			delta.Add("Spec.SubjectAlternativeNames", a.ko.Spec.SubjectAlternativeNames, b.ko.Spec.SubjectAlternativeNames)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
